In [6]:
import pandas as pd
import numpy as np

Zadanie 1 (5 pkt)


Wgraj zawartość pliku orders.csv do ramki danych.
Przyjrzyj się danym, wykorzystując poznane metody (describe, info, head) zanalizuj dane.

Następnie:



1. Zamień order_date na format daty. Upewnij się, że w rezultacie data będzie w formacie: rok-miesiąc-dzień;
2. Sprawdź ile i jakie unikalne wartości znajdują się w kolumnie T-shirt category;
3. Wyczyść kolumnę tshirt_category normalizując nazwy produktów. Upewnij się, że dla każdej kategorii funkcjonuje jedna nazwa, np. zamiast white i wh jest tylko jedna wersja white. Skorzystaj z klasy string i metody apply;
4. Rozdziel kolumnę tshirt category na 3 kolumny: tshirt_type, która będzie mówiła o tym czy jest to koszulka, bluza czy coś innego, tshirt_size, która będzie informowała o rozmiarze koszulki, i tshirt_colour, która będzie informowała o kolorze. Skorzystaj z metody apply.
5. Znajdź zamówienia złożone między 31 grudnia 2014 a 2 sierpnia 2016.

In [32]:
df=pd.read_csv('orders.csv', sep=',', encoding='utf-8', on_bad_lines='warn')
df

,order_date,pages_visited,order_id,customer_id,tshirt_category,tshirt_price,tshirt_quantity
0,2016/09/04,9,HTS-038040-0002,038040,White T-Shirt M,20.0,1
1,2014/11/14,11,HTS-801797-0001,801797,White T-Shirt M,20.0,1
2,2017/02/26,10,HTS-vft1eu-0003,vft1eu,White T-Shirt F,18.0,3
3,2013/12/01,10,HTS-914324-0001,914324,Wh Tshirt F,18.0,1
4,2015/10/22,12,HTS-88ua9r-0001,88ua9r,White T-Shirt M,20.0,1
...,...,...,...,...,...,...,...
26547,2016/11/19,13,HTS-n641x4-0001,n641x4,White T-Shirt M,20.0,1
26548,2016/08/02,4,HTS-q0nm12-0001,q0nm12,White T-Shirt M,20.0,1
26549,2017/03/09,6,HTS-sby0iz-0001,sby0iz,White T-Shirt M,20.0,1
26550,2016/10/04,11,HTS-uz70x4-0001,uz70x4,Hoodie,23.0,5
26551,2016/12/16,9,HTS-xnbc22-0001,xnbc22,Black T-Shirt M,19.0,3

In [34]:
# ad1.
df['order_date']=pd.to_datetime(df["order_date"], format="%Y/%m/%d")
#ad2
df['tshirt_category'].value_counts()
display(df['tshirt_category'].value_counts())
#ad3. 
lista_zmian={"Wh ":"White ", "Bl ":"Black ", "Tshirt":"T-Shirt"} 
#  "Tennis Shirt":"Tennis Shirt all-size" ,"Hoodie":"no-info Hoodie all-size"}
for key in lista_zmian.keys():
    df['tshirt_category']=df['tshirt_category'].apply(lambda x : x.replace(key, str(lista_zmian[key])))
display('after:',df['tshirt_category'].value_counts())
# df.head(5)

Hoodie             6229
White T-Shirt M    6009
Black T-Shirt M    4831
White T-Shirt F    3825
Black T-Shirt F    3505
Tennis Shirt       2153
Name: tshirt_category, dtype: int64

'after:'

Hoodie             6229
White T-Shirt M    6009
Black T-Shirt M    4831
White T-Shirt F    3825
Black T-Shirt F    3505
Tennis Shirt       2153
Name: tshirt_category, dtype: int64

NameError: name 'df2' is not defined

In [36]:
# Rozdziel kolumnę tshirt category na 3 kolumny: tshirt_type, która będzie mówiła o tym czy jest to koszulka,
#  bluza czy coś innego, tshirt_size, która będzie informowała o rozmiarze koszulki,
#  i tshirt_colour, która będzie informowała o kolorze. Skorzystaj z metody apply.
# df['tshirt_category'] = df['tshirt_type', 'tshirt_size', 'tshirt_color']=
# df['tshirt_category'].str.get(-1)
df['tshirt_color','tshirt_type', 'tshirt_size']=df['tshirt_category'].apply(lambda x: x.split(expand=True))
# df['tshirt_category'].apply(lambda x:x.split()[-1])
# df['tshirt_category'].str.split(expand=True)

InvalidIndexError: ('0', '1')

In [10]:
#ad5
df[(df['order_date'] >= '31/12/2014') & (df['order_date'] <='2016/08/02')]['order_id']

C:\Users\tomasz.pokrzywnicki\AppData\Roaming\Python\Python310\site-packages\pandas\core\arraylike.py:60: UserWarning: Parsing '31/12/2014' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return self._cmp_method(other, operator.ge)

4        HTS-88ua9r-0001
5        HTS-061311-0003
12       HTS-je57lh-0001
13       HTS-252675-0002
15       HTS-heb26i-0001
              ...
26496    HTS-5b4bg6-0001
26513    HTS-bt08zd-0001
26515    HTS-gsc3f6-0001
26540    HTS-6ba0i0-0001
26548    HTS-q0nm12-0001
Name: order_id, Length: 12638, dtype: object

Zadanie 2 (4 pkt)


Wgraj plik customers.csv do ramki danych. 

Następnie:
1. Wypisz kolumny;
2. Porównaj rozmiar ramki z rozmiarem ramki w zadaniu 1;
3. Zmień nazwę kolumny customerID  na customer_id upewniając się, że dane zmiana zostanie zapisana w pamięci dzięki jednemu z argumentów metody do zmiany nazwy kolumny;
4. Połącz ramkę orders z ramką customers po kolumnie customer_id. Z której metody skorzystasz? Zostaw odpowiedź w komentarzu do zadania w kodzie (np. blok komentarzem ‘’’ ‘’’).

In [25]:
customers=pd.read_csv('customers.csv', sep=',', encoding='utf-8', on_bad_lines='warn')
print("ad1. kolumny:", list(customers.columns))
print("ad2. order:", df.shape," customer:", customers.shape)
df.rename(columns={'customerID':'customer_id'}, inplace=True)
print('ad3.', df['customer_id'].head(0))

ad1. kolumny: ['customerID', 'gender', 'birthdate', 'user_agent', 'ip_address', 'campaign']
ad2. order: (26552, 7)  customer: (18766, 6)
ad3. Series([], Name: customer_id, dtype: object)

Zadanie 3 (1 pkt)

Nową ramkę (połączenie orders i customers) zapisz do pliku csv, ale zapisz bez kolumny z indeksem.

In [10]:
list(customers.columns)

['customerID', 'gender', 'birthdate', 'user_agent', 'ip_address', 'campaign']